apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitter
  name: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - image: gcr.io/bootiful/joshlong-com-api
          imagePullPolicy: Always
          name: twitter
#        - image: gcr.io/bootiful/twitter
#          #        - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
#          imagePullPolicy: Always
#          name: twitter
#          ports:
#            - containerPort: 8080

          startupProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/liveness

          env:
            - name: BLOG_INDEX_REBUILD_KEY
              valueFrom:
                secretKeyRef:
                  name: joshlong-com-api-secrets
                  key: BLOG_INDEX_REBUILD_KEY
            - name: BLOG_RESET_ON_REBUILD
              value: "true"
            - name: BLOG_API_SERVER_URI
              value: "https://api.joshlong.com"
            - name: LANG
              value: "en_US.UTF-8"

            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_PASSWORD
            - name: SPRING_R2DBC_URL
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_URL
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_USERNAME
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_PASSWORD
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_VIRTUAL_HOST
            - name: TWITTER_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_APP_CLIENT_ID
            - name: TWITTER_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_APP_CLIENT_SECRET
            - name: TWITTER_CLIENTS_0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_0_CLIENT_ID
            - name: TWITTER_CLIENTS_0_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_0_SECRET
            - name: TWITTER_CLIENTS_1_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_1_CLIENT_ID
            - name: TWITTER_CLIENTS_1_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_1_SECRET
            - name: TWITTER_ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_ENCRYPTION_PASSWORD
            - name: TWITTER_ENCRYPTION_SALT
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_ENCRYPTION_SALT
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"