apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitter
  name: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - image: gcr.io/bootiful/twitter-service
          imagePullPolicy: Always
          name: api
          env:
            - name: LANG
              value: "en_US.UTF-8"
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_PASSWORD
            - name: SPRING_R2DBC_URL
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_URL
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_R2DBC_USERNAME
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_PASSWORD
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: SPRING_RABBITMQ_VIRTUAL_HOST
            - name: TWITTER_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_APP_CLIENT_ID
            - name: TWITTER_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_APP_CLIENT_SECRET
            - name: TWITTER_CLIENTS_0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_0_CLIENT_ID
            - name: TWITTER_CLIENTS_0_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_0_SECRET
            - name: TWITTER_CLIENTS_1_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_1_CLIENT_ID
            - name: TWITTER_CLIENTS_1_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_CLIENTS_1_SECRET
            - name: TWITTER_ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_ENCRYPTION_PASSWORD
            - name: TWITTER_ENCRYPTION_SALT
              valueFrom:
                secretKeyRef:
                  name: twitter-secrets
                  key: TWITTER_ENCRYPTION_SALT
#            - name: BLOG_RESET_ON_REBUILD
#              value: "true"
#            - name: BLOG_API_SERVER_URI
#              value: "https://api.joshlong.com"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"