apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    networking.gke.io/managed-certificates: "twitter-certificate"
    kubernetes.io/ingress.global-static-ip-name: "twitter-ip"
  name: twitter-ingress
spec:
  rules:
    - host: twitter.developeradvocacy.services
      http:
        paths:
          - backend:
              serviceName: twitter
              servicePort: 80
